// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxiyv9K8ePLXIVY5XNq0Im8U8AFYfJ_rw',
    appId: '1:198085325272:web:97e15eb697464a840682ad',
    messagingSenderId: '198085325272',
    projectId: 'fluttermusiccommentapp',
    authDomain: 'fluttermusiccommentapp.firebaseapp.com',
    storageBucket: 'fluttermusiccommentapp.firebasestorage.app',
    measurementId: 'G-W5VN50G5VV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgMYH4Tg3WIKNgpIjH6xAev6cGJ2MhmAs',
    appId: '1:198085325272:android:065b8b203af9c7a60682ad',
    messagingSenderId: '198085325272',
    projectId: 'fluttermusiccommentapp',
    storageBucket: 'fluttermusiccommentapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm3Zbtp8lS6EAScOuzWzpuuhxRezcgosw',
    appId: '1:198085325272:ios:b2816713ae8e59520682ad',
    messagingSenderId: '198085325272',
    projectId: 'fluttermusiccommentapp',
    storageBucket: 'fluttermusiccommentapp.firebasestorage.app',
    iosBundleId: 'com.example.firebasecommentapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCm3Zbtp8lS6EAScOuzWzpuuhxRezcgosw',
    appId: '1:198085325272:ios:b2816713ae8e59520682ad',
    messagingSenderId: '198085325272',
    projectId: 'fluttermusiccommentapp',
    storageBucket: 'fluttermusiccommentapp.firebasestorage.app',
    iosBundleId: 'com.example.firebasecommentapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxiyv9K8ePLXIVY5XNq0Im8U8AFYfJ_rw',
    appId: '1:198085325272:web:0c509b8966e3b2dd0682ad',
    messagingSenderId: '198085325272',
    projectId: 'fluttermusiccommentapp',
    authDomain: 'fluttermusiccommentapp.firebaseapp.com',
    storageBucket: 'fluttermusiccommentapp.firebasestorage.app',
    measurementId: 'G-1QSLGW3GVL',
  );
}
